### ISSUE TITLE
Give a warning if running node < v4

### ISSUE THREAD

**Issue by Flet** [Flet/standard-engine#126]
Perhaps we should move this bit of code into standard-engine?

https://github.com/feross/standard/pull/590

**Comment by feross** [comment]
I thought about checking in `standard-engine` instead of `standard`, but I believe that `standard-engine` still works with `eslint` v2. I didn't want to break it for existing users for no good reason. If you want to do this and release a new major version, I'm 👍

**Comment by feross** [comment]
@Flet Want to send a PR to add this to `standard-engine` and remove it from `standard`, or shall I do it?

**Comment by feross** [comment]
It's actually not trivial to do this. We `require('eslint')` in `standard` so that we can pass it into `standard-engine`, and the error is thrown when `require('eslint')` is called.

So `standard-engine` would have to expose a constant that says whether we're on old node. Easier to just keep that check in `standard`. Eventually this won't be a problem as old node usage decreases.
